config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :animes do
    collection do
      get 'search'
    end
    resources :comments, only: :create
    
    resources :netabares do
      member do
        post 'change_count'
      end
    end
    
  end
  resources :users, only: :show do
    resource :relationships, only: [:create, :destroy]
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :finishes, only: [:show, :create]
  resources :messages, only: :create
  resources :rooms, only: [:create, :show]
  root to: "animes#index"
end

app/models/anime.rb
class Anime < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one :netabare, dependent: :destroy
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :good_point
  belongs_to :recommendation

  validates :title, presence: true
  validates :synopsis, presence: true
  validates :text, presence: true
  validates :image, presence: true

  with_options numericality: { other_than: 0, message: "can't be blank" } do
    validates :genre_id
    validates :good_point_id
    validates :recommendation_id
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title", "genre_id", "good_point_id", "recommendation_id"]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :anime

  belongs_to :parent,  class_name: "Comment", optional: true
  has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true, length: { in: 1..1000 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/finish.rb
class Finish < ApplicationRecord
  belongs_to :user
  with_options numericality: { other_than: 0, message: "can't be blank" } do
    validates :group_id
  end
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    {id: 1, name: 'アクション'}, {id: 2, name: 'アドベンチャー'}, 
    {id: 3, name: 'ファンタジー'}, {id: 4, name: 'SF'}, {id: 5, name: '日常'}, 
    {id: 6, name: 'バトル'}, {id: 7, name: '恋愛'}, {id: 8, name: 'ギャグ'}, 
    {id: 9, name: 'ミステリー'}, {id: 10, name: 'ホラー'}, {id: 11, name: 'スポーツ'}, 
    {id: 12, name: '音楽'}, {id: 13, name: '異世界転生'}
  ]
end

app/models/good_point.rb
class GoodPoint < ActiveHash::Base
  self.data = [
    {id: 1, name: 'ストーリー'}, {id: 2, name: '作画'}, 
    {id: 3, name: '歌'}
  ]
end

app/models/group.rb
class Group < ActiveHash::Base
  self.data = [
    {id: 1, name: 'あ行'}, {id: 2, name: 'か行'}, 
    {id: 3, name: 'さ行'}, {id: 4, name: 'た行'}, {id: 5, name: 'な行'}, 
    {id: 6, name: 'は行'}, {id: 7, name: 'ま行'}, {id: 8, name: 'や行'}, 
    {id: 9, name: 'ら行'}, {id: 10, name: 'わ行'}
  ]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/netabare.rb
class Netabare < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/recommendation.rb
class Recommendation < ActiveHash::Base
  self.data = [
    {id: 1, name: '笑える'}, {id: 2, name: '感動する'}, 
    {id: 3, name: '泣ける'}, {id: 4, name: 'ほのぼの'}, {id: 5, name: '燃える'}, 
    {id: 6, name: '萌える'}, {id: 7, name: 'ハマる'}
  ]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :animes
  has_many :comments
  has_many :netabares
  has_one :profile
  has_many :finishes

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true

  def followed_by?(user)
    follower =  passive_relationships.find_by(following_id: user.id)
    return follower.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @animes = @user.animes.order(created_at: :desc)
    @netabare = {}
    @animes.each do |anime|
      @netabare[anime.id] = Netabare.where(anime_id: anime.id).count
    end
    @profile = @user.profile
  end
=begin 
    @currentUserEntry=Entry.where(user_id: current_user.id)  #現在ログインしているユーザー
    @userEntry=Entry.where(user_id: @user.id)  #もう一人のユーザー
    if @user.id == current_user.id  #もう一人のユーザー=現在ログインしているユーザー
    else                            #ではない
      @currentUserEntry.each do |cu|  #ルームが既に作成されている場合
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom  #ルームが既に作られている状態
      else        #ではない
        @room = Room.new
        @entry = Entry.new
      end
    end
=end

end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/finishes_helper.rb
module FinishesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<!-- マイページ -->
  <div class="anime-chart-post">

    <div class="user-show-my-pages">
      <div class="user-show-my-page">
        <div class="user-show-my-page-contents">
          <div class="user-show-my-page-content">
            <div class="user-show-my-page-name-friend">
              <div class="user-show-my-page-name"> <%= "#{@user.name}さんのマイページ" %> </div>
              <% if current_user && @user != current_user %>
                <% if @user.followed_by?(current_user) %>
                  <%=link_to "フォロー解除する", user_relationships_path(@user.id), class: "user-show-link-friend-register", data: { turbo_method: :delete } %>
                <% else %>
                  <%=link_to "フォロー登録する", user_relationships_path(@user.id), class: "user-show-link-friend-register", data: { turbo_method: :post } %>
                <% end %>
              <% end %>
            </div>

            <h3 class="followings">フォロー</h3>
            <% @user.followings.each do |user| %>
              <p class=“f-users”>・<%= link_to user.name, user_path(user.id), class: "f-user" %></p>
            <% end %>
            <h3 class="followers">フォロワー</h3>
            <% @user.followers.each do |user| %>
              <p class=“f-users”>・<%= link_to user.name, user_path(user.id), class: "f-user" %></p>
            <% end %>

            <div class="user-show-end-animes">
              <%= link_to '➡観終わったアニメ一覧', finish_path(@user), class: "user-show-link-end-anime" %>
            </div>
            <% if @profile.present? %>
            <div class="user-show-tables">
              <table class="user-show-detail-table">
                <tr>
                  <td rowspan = "5", class="user-show-detail-animes">お気に入りの<br>アニメ</td>
                  <td class="user-show-detail-anime"><%= @profile.favorite1 %></td>
                </tr>
                <tr>
                  <td class="user-show-detail-anime"><%= @profile.favorite2 %></td>
                </tr>
                <tr>
                  <td class="user-show-detail-anime"><%= @profile.favorite3 %></td>
                </tr>
                <tr>
                  <td class="user-show-detail-anime"><%= @profile.favorite4 %></td>
                </tr>
                <tr>
                  <td class="user-show-detail-anime"><%= @profile.favorite5 %></td>
                </tr>
                <tr>
                  <td rowspan = "5", class="user-show-detail-free-comments">フリーコメント</td>
                  <td class="user-show-detail-free-comment"><%= simple_format(@profile.free_comment) %></td>
                </tr>
              </table>
            </div>
            <% else %>
              <p class="profile-not-found">プロフィールがまだ登録されていません。</p>
            <% end %>

            <div class="user-show-my-page-change-buttons">
              <% if user_signed_in? %>
                <% unless @user.profile.present? %>
                  <% if current_user.id == @user.id %>
                    <div class="profile-btn">
                      <%= link_to 'プロフィールを登録する', new_profile_path, class: "profile-edit-btn" %>
                    </div>
                  <% end %>
                <% end %>
                <% if current_user.id == @user.id && @user.profile.present? %>
                  <div class="profile-btn">
                    <%= link_to 'プロフィールを編集する', edit_profile_path(@user.profile.id), class: "profile-edit-btn" %>
                  </div>
                <% end %>
              <% end %> 
            </div>
          </div>
        </div>
      </div>
    </div>

<%
=begin 
%>
    <% unless @user.id == current_user.id %>

      <% if @isRoom == true %>
        <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: @user.id %>
          <% end %>
          <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
        <% end %>
      <% end %>
      
    <% end %>
<%
=end 
%>
    <div class="user-show-charts">
      <div class="user-show-anime-chart">
        <%= "#{@user.name}さんのアニメ投稿一覧"%>
      </div>
    </div>
      
    <div class="posts">
      <% @animes.each do |anime|%>
        <div class="matome">
          <div class="post">
            <div class="edited-end-edit-delete">
              <div class="edited-end">
                <div class="space-for-edit">
                  <% if anime.edited %>
                    <div class="edited-end-view">
                      <%= "編集済み" %>
                    </div>
                  <% end %>
                </div>
              </div>
              <% if current_user == anime.user %>
                <div class="edit-delete-button">
                  <div class="content-edit">
                    <%= link_to '編集', edit_anime_path(anime), class: "edit-button" %>
                  </div>
                  <div class="content-delete">
                    <%= link_to '削除', anime_path(anime), data: { turbo_method: :delete }, class: "delete-button" %>
                  </div>
                </div>
              <% end %>
            </div>
          
            <div class="anime-content">
              <a href="<%= anime_path(anime) %>" data-turbo="false" >
                <div class="content-header">
                  <div class="content-anime">
                    <div class="content-title">
                      アニメタイトル
                    </div>
                    <div class="content-anime-title">
                      <%= anime.title %>
                    </div>
                  </div>
                  <div class="content-netabare-count">
                    <div class="netabare">
                      <%= @netabare[anime.id] %>
                    </div>
                    <div class="count">
                      ネタバレカウント
                    </div>
                  </div>
                </div>
                <div class="content-middle">
                  <%= image_tag anime.image.variant(resize: '180x200!'), class: 'content-image' if anime.image.attached? %>
                </div>
                <div class="content-footer">
                  <table class="detail-table">
                    <tbody>
                      <tr>
                        <th class="detail-anime">ジャンル</th>
                        <td class="detail-value"><%= anime.genre.name %></td>
                      </tr>
                      <tr>
                        <th class="detail-anime">良いところ</th>
                        <td class="detail-value"><%= anime.good_point.name %></td>
                      </tr>
                      <tr>
                        <th class="detail-anime">どんな人におすすめか</th>
                        <td class="detail-value"><%= anime.recommendation.name %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>