config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :animes do
    collection do
      get 'search'
    end
    resources :comments, only: :create
    
    resources :netabares do
      member do
        post 'change_count'
      end
    end
    
  end
  resources :users, only: :show do
    resource :relationships, only: [:create, :destroy]
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :finishes, only: [:show, :create]
  resources :messages, only: :create
  resources :rooms, only: [:create, :show]
  root to: "animes#index"
end

app/models/anime.rb
class Anime < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one :netabare, dependent: :destroy
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :good_point
  belongs_to :recommendation

  validates :title, presence: true
  validates :synopsis, presence: true
  validates :text, presence: true
  validates :image, presence: true

  with_options numericality: { other_than: 0, message: "can't be blank" } do
    validates :genre_id
    validates :good_point_id
    validates :recommendation_id
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title", "genre_id", "good_point_id", "recommendation_id"]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :anime

  belongs_to :parent,  class_name: "Comment", optional: true
  has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true, length: { in: 1..1000 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/finish.rb
class Finish < ApplicationRecord
  belongs_to :user
  with_options numericality: { other_than: 0, message: "can't be blank" } do
    validates :group_id
  end
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    {id: 1, name: 'アクション'}, {id: 2, name: 'アドベンチャー'}, 
    {id: 3, name: 'ファンタジー'}, {id: 4, name: 'SF'}, {id: 5, name: '日常'}, 
    {id: 6, name: 'バトル'}, {id: 7, name: '恋愛'}, {id: 8, name: 'ギャグ'}, 
    {id: 9, name: 'ミステリー'}, {id: 10, name: 'ホラー'}, {id: 11, name: 'スポーツ'}, 
    {id: 12, name: '音楽'}, {id: 13, name: '異世界転生'}
  ]
end

app/models/good_point.rb
class GoodPoint < ActiveHash::Base
  self.data = [
    {id: 1, name: 'ストーリー'}, {id: 2, name: '作画'}, 
    {id: 3, name: '歌'}
  ]
end

app/models/group.rb
class Group < ActiveHash::Base
  self.data = [
    {id: 1, name: 'あ行'}, {id: 2, name: 'か行'}, 
    {id: 3, name: 'さ行'}, {id: 4, name: 'た行'}, {id: 5, name: 'な行'}, 
    {id: 6, name: 'は行'}, {id: 7, name: 'ま行'}, {id: 8, name: 'や行'}, 
    {id: 9, name: 'ら行'}, {id: 10, name: 'わ行'}
  ]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/netabare.rb
class Netabare < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/recommendation.rb
class Recommendation < ActiveHash::Base
  self.data = [
    {id: 1, name: '笑える'}, {id: 2, name: '感動する'}, 
    {id: 3, name: '泣ける'}, {id: 4, name: 'ほのぼの'}, {id: 5, name: '燃える'}, 
    {id: 6, name: '萌える'}, {id: 7, name: 'ハマる'}
  ]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :animes
  has_many :comments
  has_many :netabares
  has_one :profile
  has_many :finishes

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true

  def followed_by?(user)
    follower =  passive_relationships.find_by(following_id: user.id)
    return follower.present?
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :redirect_to_index, only: [:edit, :update, :destroy]
  def index
    @animes = Anime.all.order(created_at: :desc)
    @q = Anime.ransack(params[:q])
    @q.combinator = 'or'
    animes = @q.result(distinct: true)
    @netabare = {}
    @animes.each do |anime|
      @netabare[anime.id] = Netabare.where(anime_id: anime.id).count
    end
  end

  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)
    if @anime.save
      return redirect_to root_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @anime = Anime.find(params[:id])
    session[:previous_url] = request.referer
  end

  def update
    @anime = Anime.find(params[:id])
     if @anime.update(anime_params)
      @anime.update(edited: true)
      redirect_to session[:previous_url] || root_path
     else
      render :edit, status: :unprocessable_entity
     end
  end

  def destroy
    anime = Anime.find(params[:id])
    anime.destroy
    redirect_to user_path(anime.user)
  end

  def show
    @anime = Anime.find(params[:id])
    @comments = @anime.comments
    @comment = Comment.new
    @comment_reply = @anime.comments.new
    @netabares = Netabare.where(anime_id: @anime.id)
    @netabare = Netabare.new
  end

  def search
    @q = Anime.ransack(params[:q])
    @q.combinator = 'or'
    @animes = @q.result(distinct: true).order(created_at: :desc)
    @netabare = {}
    @animes.each do |anime|
      @netabare[anime.id] = Netabare.where(anime_id: anime.id).count
    end
  end

  private
  def anime_params
    params.require(:anime).permit(:title, :synopsis, :genre_id, :good_point_id, :recommendation_id, :text, :image).merge(user_id: current_user.id)
  end

  def redirect_to_index
    @anime = Anime.find(params[:id])
    return redirect_to root_path if current_user.id != @anime.user.id 
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/finishes_helper.rb
module FinishesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animes/edit.html.erb
    <!-- 編集画面 -->
    <div class="new-anime">
      <div class="new-anime-posts">
        <div class="new-anime-post">投稿内容を変更</div>
        <div class="new-anime-post-form">
        <%= form_with model: @anime, data: {turbo: false}, local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
          <div class="new-form">
            <%= f.label :title, "アニメタイトル" %><br />
            <%= f.text_field :title, id:"anime-title", class: "new-anime-title" %>
          </div>
          <div class="new-form">
            <%= f.label :image, "アニメ画像" %><br>
            <%= f.file_field :image, id:"anime-image", class: "new-anime-image" %>
          </div>
          <div class="new-form">
            <%= f.label :synopsis, "あらすじ" %><br />
            <%= f.text_area :synopsis, id:"anime-synopsis", class: "new-anime-synopsis" %>
          </div>
          <div class="new-form">
            <%= f.label :genre_id, "ジャンル" %><br />
            <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: '--'}, class: "new-anime-genre" %>
          </div>
          <div class="new-form">
            <%= f.label :good_point_id, "良いところ" %><br />
            <%= f.collection_select :good_point_id, GoodPoint.all, :id, :name, {prompt: '--'}, class: "new-anime-good_point" %>
          </div>
          <div class="new-form">
            <%= f.label :recommendation_id, "どんな人におすすめか" %><br />
            <%= f.collection_select :recommendation_id, Recommendation.all, :id, :name, {prompt: '--'}, class: "new-anime-recommendation" %>
          </div>
          <div class="new-form">
            <%= f.label :text, "アニメを観た感想" %><br />
            <%= f.text_area :text, id:"anime-text", class: "new-anime-text" %>
          </div>
          <div class="new-form">
            <%= f.submit "編集" ,class:"new-anime-submit" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/animes/index.html.erb
<!-- サービス紹介 -->
  <div class="service-items">

    <div class="service-item">
      <div class="service-image">
        <%= image_tag 'search-window.jpg', class: 'card-logo'%>
      </div>
      <div class="service-text">
        <div class="service-text__main">
          アニメを検索しよう
        </div>
        <div class="service-text__sub">
          「アニメタイトル」、「ジャンル」、「良いところ」、「どんな人におすすめか」の4つの項目から検索できます。
        </div>
      </div>
    </div>

    <div class="service-item">
      <div class="service-image">
        <%= image_tag 'upload.jpg', class: 'card-logo'%>
      </div>
      <div class="service-text">
        <div class="service-text__main">
          アニメを投稿しよう
        </div>
        <div class="service-text__sub">
          おすすめしたいアニメを投稿できます。ネタバレ注意！（＊ログイン/新規登録が必要です＊）
        </div>
      </div>
    </div>

    <div class="service-item">
      <div class="service-image">
        <%= image_tag 'netabare-click.jpg', class: 'card-logo'%>
      </div>
      <div class="service-text">
        <div class="service-text__main">
          ネタバレボタンをクリックしよう
        </div>
        <div class="service-text__sub">
          投稿されたアニメを見て、ネタバレがあると思ったらネタバレボタンをクリックできます。（＊ログイン/新規登録が必要です＊）
        </div>
      </div>
    </div>
  </div>

<!-- アニメ投稿一覧 -->
  <div class="anime-chart-post">
    <div class="charts">
      <div class="anime-chart">アニメ投稿一覧</div>
      <% if user_signed_in? %>
        <%= link_to '新規投稿', new_anime_path, class:"new-post-submit"%>
      <% end %>
    </div>

    <div class="search-forms">
      <%= search_form_for @q, url: search_animes_path, html: {id: "detailed-search-form"} do |form| %>
        <div class="form">
          <div class="search-form">
            <%= form.label :title_cont, "アニメタイトル" %><br />
            <%= form.text_field :title_cont, placeholder: 'アニメタイトルを入力', class: 'search-anime-title' %>
          </div>
          <div class="search-form">
            <%= form.label :genre_id_eq, "ジャンル" %><br />
            <%= form.collection_select(:genre_id_eq, Genre.all, :id, :name, {include_blank: "--"}, { class: 'search-anime-ids' }) %>
          </div>
          <div class="search-form">
            <%= form.label :good_point_id_eq, "良いところ" %><br />
            <%= form.collection_select(:good_point_id_eq, GoodPoint.all, :id, :name, {include_blank: "--"}, { class: 'search-anime-ids' }) %>
          </div>
          <div class="search-form">
            <%= form.label :recommendation_id_eq, "どんな人におすすめか" %><br />
            <%= form.collection_select(:recommendation_id_eq, Recommendation.all, :id, :name, {include_blank: "--"}, { class: 'search-anime-ids' }) %>
          </div>
          <div class="search-form">
            <%= form.submit '検索', class: 'search-anime-submit' %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="posts">
      <% @animes.each do |anime| %>
        <div class="matome">
          <div class="space-for-edit">
            <% if anime.edited %>
              <div class="edited-end-view"><%= "編集済み" %></div>
            <% end %>
          </div>
          <div class="post">
            <div class="anime-content">
              <a href="<%= anime_path(anime) %>" data-turbo="false" >
                <div class="content-header">
                  <div class="content-anime">
                    <div class="content-title">
                      アニメタイトル
                    </div>
                    <div class="content-anime-title">
                      <%= anime.title %>
                    </div>
                  </div>
                  <div class="content-netabare-count">
                    <div class="netabare">
                      <%= @netabare[anime.id] %>
                    </div>
                    <div class="count">ネタバレカウント</div>
                  </div>
                </div>
                <div class="content-middle">
                  <%= image_tag anime.image.variant(resize: "180x200!"), class: 'content-image' if anime.image.attached? %>
                </div>
                <div class="content-footer">
                  <table class="detail-table">
                    <tbody>
                      <tr>
                        <th class="detail-anime">ジャンル</th>
                        <td class="detail-value"><%= anime.genre.name %></td>
                      </tr>
                      <tr>
                        <th class="detail-anime">良いところ</th>
                        <td class="detail-value"><%= anime.good_point.name %></td>
                      </tr>
                      <tr>
                        <th class="detail-anime">どんな人におすすめか</th>
                        <td class="detail-value"><%= anime.recommendation.name %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </a>
            </div>

            <div class="content-user-name">
              投稿者：<%= link_to anime.user.name, user_path(anime.user), class: 'user-name'%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/animes/new.html.erb
<!-- 新規投稿 -->
  <div class="new-anime">
    <div class="new-anime-posts">
      <div class="new-anime-post">アニメ新規投稿</div>
      <div class="new-anime-post-form">
        <%= form_with model: @anime, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          <div class="new-form">
            <%= f.label :title, "アニメタイトル" %><br />
            <%= f.text_field :title, id:"anime-title", class: "new-anime-title" %>
          </div>
          <div class="new-form">
            <%= f.label :image, "アニメ画像" %><br>
            <%= f.file_field :image, id:"anime-image", class: "new-anime-image" %>
          </div>
          <div class="new-form">
            <%= f.label :synopsis, "あらすじ" %><br />
            <%= f.text_area :synopsis, id:"anime-synopsis", class: "new-anime-synopsis" %>
          </div>
          <div class="new-form">
            <%= f.label :genre_id, "ジャンル" %><br />
            <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: '--'}, class: "new-anime-genre" %>
          </div>
          <div class="new-form">
            <%= f.label :good_point_id, "良いところ" %><br />
            <%= f.collection_select :good_point_id, GoodPoint.all, :id, :name, {prompt: '--'}, class: "new-anime-good_point" %>
          </div>
          <div class="new-form">
            <%= f.label :recommendation_id, "どんな人におすすめか" %><br />
            <%= f.collection_select :recommendation_id, Recommendation.all, :id, :name, {prompt: '--'}, class: "new-anime-recommendation" %>
          </div>
          <div class="new-form">
            <%= f.label :text, "アニメを観た感想" %><br />
            <%= f.text_area :text, id:"anime-text", class: "new-anime-text" %>
          </div>
          <div class="new-form">
            <%= f.submit "新規投稿", class:"new-anime-submit" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/animes/search.html.erb
<!-- 検索結果ページ -->
  <div class="anime-chart-post">
    <div class="search-charts">
      <div class="search-anime-chart">検索結果一覧</div>
    </div>

    <div class="search-forms">
      <%= search_form_for @q, url: search_animes_path, html: {id: "detailed-search-form"} do |form| %>
        <div class="form">
          <div class="search-form">
            <%= form.label :title_cont, "アニメタイトル" %><br />
            <%= form.text_field :title_cont, placeholder: 'アニメタイトルを入力', class: 'search-anime-title' %>
          </div>
          <div class="search-form">
            <%= form.label :genre_id_eq, "ジャンル" %><br />
            <%= form.collection_select(:genre_id_eq, Genre.all, :id, :name, {include_blank: "--"}, { class: 'search-anime-ids' }) %>
          </div>
          <div class="search-form">
            <%= form.label :good_point_id_eq, "良いところ" %><br />
            <%= form.collection_select(:good_point_id_eq, GoodPoint.all, :id, :name, {include_blank: "--"}, { class: 'search-anime-ids' }) %>
          </div>
          <div class="search-form">
            <%= form.label :recommendation_id_eq, "どんな人におすすめか" %><br />
            <%= form.collection_select(:recommendation_id_eq, Recommendation.all, :id, :name, {include_blank: "--"}, { class: 'search-anime-ids' }) %>
          </div>
          <div class="search-form">
            <%= form.submit '検索', class: 'search-anime-submit' %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="posts">
      <% @animes.each do |anime| %>
        <div class="matome">
          <div class="post">
            <div class="space-for-edit">
              <% if anime.edited %>
                <div class="edited-end-view"><%= "編集済み" %></div>
              <% end %>
            </div>

            <div class="anime-content">
              <a href="<%= anime_path(anime) %>" data-turbo="false" >
                <div class="content-header">
                  <div class="content-anime">
                    <div class="content-title">
                      アニメタイトル
                    </div>
                    <div class="content-anime-title">
                      <%= anime.title %>
                    </div>
                  </div>
                  <div class="content-netabare-count">
                    <div class="netabare">
                      <%= @netabare[anime.id] %>
                    </div>
                    <div class="count">ネタバレカウント</div>
                  </div>
                </div>
                <div class="content-middle">
                  <%= image_tag anime.image.variant(resize: '180x200!'), class: 'content-image' if anime.image.attached? %>
                </div>
                <div class="content-footer">
                  <table class="detail-table">
                    <tbody>
                      <tr>
                        <th class="detail-anime">ジャンル</th>
                        <td class="detail-value"><%= anime.genre.name %></td>
                      </tr>
                      <tr>
                        <th class="detail-anime">良いところ</th>
                        <td class="detail-value"><%= anime.good_point.name %></td>
                      </tr>
                      <tr>
                        <th class="detail-anime">どんな人におすすめか</th>
                        <td class="detail-value"><%= anime.recommendation.name %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </a>
            </div>

            <div class="content-user-name">
              投稿者：<%= link_to anime.user.name, user_path(anime.user), class: 'user-name'%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/animes/show.html.erb
<!-- 詳細ページ -->
  <div class="show-post-comment">
    <div class="show-posts">
      <div class="show-post">
        <div class="edited-end-edit-delete">
          <div class="edited-end">
            <% if @anime.edited %>
              <div class="edited-end-view">
                <%= "編集済み" %>
              </div>
            <% end %>
          </div>
          <% if current_user == @anime.user %>
            <div class="edit-delete-button">
              <div class="content-edit">
                <%= link_to '編集', edit_anime_path(@anime), class: "edit-button" %>
              </div>
              <div class="content-delete">
                <%= link_to '削除', anime_path(@anime), data: { turbo_method: :delete }, class: "delete-button" %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="show-anime-content">
          <div class="show-anime-content-header">
            <div class="show-anime-header-left">
              <%= image_tag @anime.image.variant(resize: '300x300!'), class: 'show-anime-image' if @anime.image.attached? %>
            </div>
            <div class="show-anime-header-right">
              <div class="show-anime-title-user">
                <div class="show-anime-title">アニメタイトル</div>
                <div class="show-anime-title-name">
                  <%= @anime.title %>
                </div>
                <div class="show-anime-user-name">
                  投稿者：<%= link_to @anime.user.name, user_path(@anime.user), class: 'user-name'%>
                </div>
              </div>
              <div class="show-anime-netabare">
                <div class="show-anime-netabare-counter">
                  <div class="show-anime-netabare-count-number" id="netabare-count"><%= @netabares.where(anime_id: @anime.id).count %></div>
                  <div class="show-anime-netabare-count">ネタバレカウント</div>
                </div>
                <div class="show-anime-netabare-button">
                  <% if user_signed_in? && current_user != @anime.user %>
                    <div class="show-anime-netabare-button-form" id="netabare-buttons">
                      <%= form_tag(change_count_anime_netabare_path(@anime), method: :post, data: {turbo: false}, id: "change_count-form") do %>
                        <%= submit_tag "ネタバレ！", id: "change_count-button" %>
                      <% end %>
                    </div>
                  <% elsif current_user == @anime.user%>
                    <div class="show-anime-netabare-not-button-form">
                      自分の投稿にはネタバレ！できません
                    </div>
                  <% else %>
                    <div class="show-anime-netabare-button-form">
                      <%= button_to "ネタバレ！にはログインが必要です", new_user_session_path %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          
          <div class="show-anime-content-footer">
            <table class="show-anime-detail-table">
              <tbody>
                <tr>
                  <th class="show-anime-detail-anime">あらすじ</th>
                  <td class="show-anime-detail-value"><%= @anime.synopsis %></td>
                </tr>
                <tr>
                  <th class="show-anime-detail-anime">ジャンル</th>
                  <td class="show-anime-detail-value"><%= @anime.genre.name %></td>
                </tr>
                <tr>
                  <th class="show-anime-detail-anime">良いところ</th>
                  <td class="show-anime-detail-value"><%= @anime.good_point.name %></td>
                </tr>
                <tr>
                  <th class="show-anime-detail-anime">どんな人におすすめか</th>
                  <td class="show-anime-detail-value"><%= @anime.recommendation.name %></td>
                </tr>
                <tr>
                  <th class="show-anime-detail-anime">アニメを観た感想</th>
                  <td class="show-anime-detail-value"><%= simple_format(@anime.text) %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

<!-- コメント一覧 -->
    <div class="comments-replies">
      <div class="comments-container">
        <div class="container">
          <div class="comments-questions">コメントや質問</div>
        </div>
        <div class="accordion">
          <% @comments.each do |comment| %>
            <% if comment.parent_id.present? || comment.id.blank? %>
              <% next %>
            <% end %>
            <dl class="accordion-box">
              <dt id="question"><span></span>
                <div id="comment_area">
                  <p> <%= comment.user.name %> さん : <%= comment.created_at.strftime("%Y/%m/%d %H:%M") %></p>
                  <p> <%= comment.content %></p>
                </div>
                <div id="reply_area">
                  <% comment.replies.order(:created_at).each do |reply| %>
                    <p> <%= reply.user.name %> さん : <%= reply.created_at.strftime("%Y/%m/%d %H:%M") %></p>
                    <p> <%= reply.content %></p>
                  <% end %>
                </div>
              </dt><!-- /.question -->
              <dd id="answer">
                <% if user_signed_in? %>
                  <%= form_with model:[@anime, @comment_reply] , data: {turbo: false} do |form| %>
                    <div class="row">
                      <div class="reply-form col-md-6">
                        <%= form.text_area :content, class: "reply-form", rows: 3, placeholder: "返信を入力してください" %>
                      </div>
                    </div>
                    <%= form.hidden_field :anime_id, value: @anime.id %>
                    <%= form.hidden_field :parent_id, value: comment.id %>
                    <div class="reply-actions">
                      <%= form.submit '返信する'%>
                    </div>
                  <% end %>
                <% else %>
                  <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
                <% end %>
              </dd><!-- /.answer -->
            </dl><!-- /.accordion-box -->
          <% end %>
        </div>
        <div class="comment-forms-area">
          <div class="comment-form-area">
            <div class="comment-question">
              コメントや質問を記入
            </div>
            <% if user_signed_in? %>
              <%= form_with model:[@anime,@comment], data: {turbo: false} do |form| %>
                <%= form.text_area :content, class: "comment-form", rows: 5, placeholder: "コメントや質問を入力してください" %>
                <%= form.hidden_field :anime_id, value: @anime.id %>
                <div class="comment-actions">
                  <%= form.submit '送信する' %>
                </div>
              <% end %>
            <% else %>
              <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>